//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, внесенные в этот файл, могут привести к неверному выполнению кода и будут потеряны
//     в случае его повторного формирования.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Horizont.Claims.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Address))]
    [KnownType(typeof(CommonClaim))]
    [KnownType(typeof(CommonFailure))]
    [KnownType(typeof(Disp))]
    [KnownType(typeof(Journal))]
    public partial class CommonClaimHistoryItem: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Свойства-примитивы
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("Свойство Id является частью ключа объекта, поэтому его нельзя изменить. Ключевые свойства можно изменять только в тех случаях, когда объект не отслеживается или находится в состоянии добавления.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public Nullable<int> ClaimId
        {
            get { return _claimId; }
            set
            {
                if (_claimId != value)
                {
                    ChangeTracker.RecordOriginalValue("ClaimId", _claimId);
                    if (!IsDeserializing)
                    {
                        if (CommonClaim != null && CommonClaim.Id != value)
                        {
                            CommonClaim = null;
                        }
                    }
                    _claimId = value;
                    OnPropertyChanged("ClaimId");
                }
            }
        }
        private Nullable<int> _claimId;
    
        [DataMember]
        public Nullable<int> JournalId
        {
            get { return _journalId; }
            set
            {
                if (_journalId != value)
                {
                    ChangeTracker.RecordOriginalValue("JournalId", _journalId);
                    if (!IsDeserializing)
                    {
                        if (Journal != null && Journal.Id != value)
                        {
                            Journal = null;
                        }
                    }
                    _journalId = value;
                    OnPropertyChanged("JournalId");
                }
            }
        }
        private Nullable<int> _journalId;
    
        [DataMember]
        public Nullable<int> AddressId
        {
            get { return _addressId; }
            set
            {
                if (_addressId != value)
                {
                    ChangeTracker.RecordOriginalValue("AddressId", _addressId);
                    if (!IsDeserializing)
                    {
                        if (Address != null && Address.Id != value)
                        {
                            Address = null;
                        }
                    }
                    _addressId = value;
                    OnPropertyChanged("AddressId");
                }
            }
        }
        private Nullable<int> _addressId;
    
        [DataMember]
        public Nullable<int> Flat
        {
            get { return _flat; }
            set
            {
                if (_flat != value)
                {
                    _flat = value;
                    OnPropertyChanged("Flat");
                }
            }
        }
        private Nullable<int> _flat;
    
        [DataMember]
        public Nullable<int> Doorway
        {
            get { return _doorway; }
            set
            {
                if (_doorway != value)
                {
                    _doorway = value;
                    OnPropertyChanged("Doorway");
                }
            }
        }
        private Nullable<int> _doorway;
    
        [DataMember]
        public Nullable<int> Floor
        {
            get { return _floor; }
            set
            {
                if (_floor != value)
                {
                    _floor = value;
                    OnPropertyChanged("Floor");
                }
            }
        }
        private Nullable<int> _floor;
    
        [DataMember]
        public string Phone
        {
            get { return _phone; }
            set
            {
                if (_phone != value)
                {
                    _phone = value;
                    OnPropertyChanged("Phone");
                }
            }
        }
        private string _phone;
    
        [DataMember]
        public string Code
        {
            get { return _code; }
            set
            {
                if (_code != value)
                {
                    _code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        private string _code;
    
        [DataMember]
        public string CommonFailureStr
        {
            get { return _commonFailureStr; }
            set
            {
                if (_commonFailureStr != value)
                {
                    _commonFailureStr = value;
                    OnPropertyChanged("CommonFailureStr");
                }
            }
        }
        private string _commonFailureStr;
    
        [DataMember]
        public Nullable<int> ExecutedPeriod
        {
            get { return _executedPeriod; }
            set
            {
                if (_executedPeriod != value)
                {
                    _executedPeriod = value;
                    OnPropertyChanged("ExecutedPeriod");
                }
            }
        }
        private Nullable<int> _executedPeriod;
    
        [DataMember]
        public string CommonFailureComment
        {
            get { return _commonFailureComment; }
            set
            {
                if (_commonFailureComment != value)
                {
                    _commonFailureComment = value;
                    OnPropertyChanged("CommonFailureComment");
                }
            }
        }
        private string _commonFailureComment;
    
        [DataMember]
        public string ReceivedOperator
        {
            get { return _receivedOperator; }
            set
            {
                if (_receivedOperator != value)
                {
                    _receivedOperator = value;
                    OnPropertyChanged("ReceivedOperator");
                }
            }
        }
        private string _receivedOperator;
    
        [DataMember]
        public Nullable<System.DateTime> ReceivedTime
        {
            get { return _receivedTime; }
            set
            {
                if (_receivedTime != value)
                {
                    _receivedTime = value;
                    OnPropertyChanged("ReceivedTime");
                }
            }
        }
        private Nullable<System.DateTime> _receivedTime;
    
        [DataMember]
        public string OrgName
        {
            get { return _orgName; }
            set
            {
                if (_orgName != value)
                {
                    _orgName = value;
                    OnPropertyChanged("OrgName");
                }
            }
        }
        private string _orgName;
    
        [DataMember]
        public Nullable<int> IsTeam
        {
            get { return _isTeam; }
            set
            {
                if (_isTeam != value)
                {
                    _isTeam = value;
                    OnPropertyChanged("IsTeam");
                }
            }
        }
        private Nullable<int> _isTeam;
    
        [DataMember]
        public Nullable<bool> IsSubmission
        {
            get { return _isSubmission; }
            set
            {
                if (_isSubmission != value)
                {
                    _isSubmission = value;
                    OnPropertyChanged("IsSubmission");
                }
            }
        }
        private Nullable<bool> _isSubmission;
    
        [DataMember]
        public Nullable<System.DateTime> SubmissionTime
        {
            get { return _submissionTime; }
            set
            {
                if (_submissionTime != value)
                {
                    _submissionTime = value;
                    OnPropertyChanged("SubmissionTime");
                }
            }
        }
        private Nullable<System.DateTime> _submissionTime;
    
        [DataMember]
        public Nullable<bool> IsLegate
        {
            get { return _isLegate; }
            set
            {
                if (_isLegate != value)
                {
                    _isLegate = value;
                    OnPropertyChanged("IsLegate");
                }
            }
        }
        private Nullable<bool> _isLegate;
    
        [DataMember]
        public Nullable<int> Result
        {
            get { return _result; }
            set
            {
                if (_result != value)
                {
                    _result = value;
                    OnPropertyChanged("Result");
                }
            }
        }
        private Nullable<int> _result;
    
        [DataMember]
        public string Typework
        {
            get { return _typework; }
            set
            {
                if (_typework != value)
                {
                    _typework = value;
                    OnPropertyChanged("Typework");
                }
            }
        }
        private string _typework;
    
        [DataMember]
        public string Executor
        {
            get { return _executor; }
            set
            {
                if (_executor != value)
                {
                    _executor = value;
                    OnPropertyChanged("Executor");
                }
            }
        }
        private string _executor;
    
        [DataMember]
        public Nullable<bool> IsCheck
        {
            get { return _isCheck; }
            set
            {
                if (_isCheck != value)
                {
                    _isCheck = value;
                    OnPropertyChanged("IsCheck");
                }
            }
        }
        private Nullable<bool> _isCheck;
    
        [DataMember]
        public string ExecutedOperator
        {
            get { return _executedOperator; }
            set
            {
                if (_executedOperator != value)
                {
                    _executedOperator = value;
                    OnPropertyChanged("ExecutedOperator");
                }
            }
        }
        private string _executedOperator;
    
        [DataMember]
        public Nullable<System.DateTime> ExecutedTime
        {
            get { return _executedTime; }
            set
            {
                if (_executedTime != value)
                {
                    _executedTime = value;
                    OnPropertyChanged("ExecutedTime");
                }
            }
        }
        private Nullable<System.DateTime> _executedTime;
    
        [DataMember]
        public Nullable<int> DispId
        {
            get { return _dispId; }
            set
            {
                if (_dispId != value)
                {
                    ChangeTracker.RecordOriginalValue("DispId", _dispId);
                    if (!IsDeserializing)
                    {
                        if (Disp != null && Disp.Id != value)
                        {
                            Disp = null;
                        }
                    }
                    _dispId = value;
                    OnPropertyChanged("DispId");
                }
            }
        }
        private Nullable<int> _dispId;
    
        [DataMember]
        public string RegNumber
        {
            get { return _regNumber; }
            set
            {
                if (_regNumber != value)
                {
                    _regNumber = value;
                    OnPropertyChanged("RegNumber");
                }
            }
        }
        private string _regNumber;
    
        [DataMember]
        public Nullable<int> CommonFailureId
        {
            get { return _commonFailureId; }
            set
            {
                if (_commonFailureId != value)
                {
                    ChangeTracker.RecordOriginalValue("CommonFailureId", _commonFailureId);
                    if (!IsDeserializing)
                    {
                        if (CommonFailure != null && CommonFailure.Id != value)
                        {
                            CommonFailure = null;
                        }
                    }
                    _commonFailureId = value;
                    OnPropertyChanged("CommonFailureId");
                }
            }
        }
        private Nullable<int> _commonFailureId;
    
        [DataMember]
        public string SubmissionOperator
        {
            get { return _submissionOperator; }
            set
            {
                if (_submissionOperator != value)
                {
                    _submissionOperator = value;
                    OnPropertyChanged("SubmissionOperator");
                }
            }
        }
        private string _submissionOperator;
    
        [DataMember]
        public string Owner
        {
            get { return _owner; }
            set
            {
                if (_owner != value)
                {
                    _owner = value;
                    OnPropertyChanged("Owner");
                }
            }
        }
        private string _owner;
    
        [DataMember]
        public Nullable<System.DateTime> ChangeTime
        {
            get { return _changeTime; }
            set
            {
                if (_changeTime != value)
                {
                    _changeTime = value;
                    OnPropertyChanged("ChangeTime");
                }
            }
        }
        private Nullable<System.DateTime> _changeTime;
    
        [DataMember]
        public string ChangeOperator
        {
            get { return _changeOperator; }
            set
            {
                if (_changeOperator != value)
                {
                    _changeOperator = value;
                    OnPropertyChanged("ChangeOperator");
                }
            }
        }
        private string _changeOperator;
    
        [DataMember]
        public Nullable<int> ChangeId
        {
            get { return _changeId; }
            set
            {
                if (_changeId != value)
                {
                    _changeId = value;
                    OnPropertyChanged("ChangeId");
                }
            }
        }
        private Nullable<int> _changeId;

        #endregion

        #region Свойства навигации
    
        [DataMember]
        public Address Address
        {
            get { return _address; }
            set
            {
                if (!ReferenceEquals(_address, value))
                {
                    var previousValue = _address;
                    _address = value;
                    FixupAddress(previousValue);
                    OnNavigationPropertyChanged("Address");
                }
            }
        }
        private Address _address;
    
        [DataMember]
        public CommonClaim CommonClaim
        {
            get { return _commonClaim; }
            set
            {
                if (!ReferenceEquals(_commonClaim, value))
                {
                    var previousValue = _commonClaim;
                    _commonClaim = value;
                    FixupCommonClaim(previousValue);
                    OnNavigationPropertyChanged("CommonClaim");
                }
            }
        }
        private CommonClaim _commonClaim;
    
        [DataMember]
        public CommonFailure CommonFailure
        {
            get { return _commonFailure; }
            set
            {
                if (!ReferenceEquals(_commonFailure, value))
                {
                    var previousValue = _commonFailure;
                    _commonFailure = value;
                    FixupCommonFailure(previousValue);
                    OnNavigationPropertyChanged("CommonFailure");
                }
            }
        }
        private CommonFailure _commonFailure;
    
        [DataMember]
        public Disp Disp
        {
            get { return _disp; }
            set
            {
                if (!ReferenceEquals(_disp, value))
                {
                    var previousValue = _disp;
                    _disp = value;
                    FixupDisp(previousValue);
                    OnNavigationPropertyChanged("Disp");
                }
            }
        }
        private Disp _disp;
    
        [DataMember]
        public Journal Journal
        {
            get { return _journal; }
            set
            {
                if (!ReferenceEquals(_journal, value))
                {
                    var previousValue = _journal;
                    _journal = value;
                    FixupJournal(previousValue);
                    OnNavigationPropertyChanged("Journal");
                }
            }
        }
        private Journal _journal;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Address = null;
            CommonClaim = null;
            CommonFailure = null;
            Disp = null;
            Journal = null;
        }

        #endregion

        #region Исправление ассоциаций
    
        private void FixupAddress(Address previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.CommonClaimsHistories.Contains(this))
            {
                previousValue.CommonClaimsHistories.Remove(this);
            }
    
            if (Address != null)
            {
                if (!Address.CommonClaimsHistories.Contains(this))
                {
                    Address.CommonClaimsHistories.Add(this);
                }
    
                AddressId = Address.Id;
            }
            else if (!skipKeys)
            {
                AddressId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Address")
                    && (ChangeTracker.OriginalValues["Address"] == Address))
                {
                    ChangeTracker.OriginalValues.Remove("Address");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Address", previousValue);
                }
                if (Address != null && !Address.ChangeTracker.ChangeTrackingEnabled)
                {
                    Address.StartTracking();
                }
            }
        }
    
        private void FixupCommonClaim(CommonClaim previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (CommonClaim != null)
            {
                ClaimId = CommonClaim.Id;
            }
    
            else if (!skipKeys)
            {
                ClaimId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("CommonClaim")
                    && (ChangeTracker.OriginalValues["CommonClaim"] == CommonClaim))
                {
                    ChangeTracker.OriginalValues.Remove("CommonClaim");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("CommonClaim", previousValue);
                }
                if (CommonClaim != null && !CommonClaim.ChangeTracker.ChangeTrackingEnabled)
                {
                    CommonClaim.StartTracking();
                }
            }
        }
    
        private void FixupCommonFailure(CommonFailure previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (CommonFailure != null)
            {
                CommonFailureId = CommonFailure.Id;
            }
    
            else if (!skipKeys)
            {
                CommonFailureId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("CommonFailure")
                    && (ChangeTracker.OriginalValues["CommonFailure"] == CommonFailure))
                {
                    ChangeTracker.OriginalValues.Remove("CommonFailure");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("CommonFailure", previousValue);
                }
                if (CommonFailure != null && !CommonFailure.ChangeTracker.ChangeTrackingEnabled)
                {
                    CommonFailure.StartTracking();
                }
            }
        }
    
        private void FixupDisp(Disp previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (Disp != null)
            {
                DispId = Disp.Id;
            }
    
            else if (!skipKeys)
            {
                DispId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Disp")
                    && (ChangeTracker.OriginalValues["Disp"] == Disp))
                {
                    ChangeTracker.OriginalValues.Remove("Disp");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Disp", previousValue);
                }
                if (Disp != null && !Disp.ChangeTracker.ChangeTrackingEnabled)
                {
                    Disp.StartTracking();
                }
            }
        }
    
        private void FixupJournal(Journal previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.CommonClaimsHistories.Contains(this))
            {
                previousValue.CommonClaimsHistories.Remove(this);
            }
    
            if (Journal != null)
            {
                if (!Journal.CommonClaimsHistories.Contains(this))
                {
                    Journal.CommonClaimsHistories.Add(this);
                }
    
                JournalId = Journal.Id;
            }
            else if (!skipKeys)
            {
                JournalId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Journal")
                    && (ChangeTracker.OriginalValues["Journal"] == Journal))
                {
                    ChangeTracker.OriginalValues.Remove("Journal");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Journal", previousValue);
                }
                if (Journal != null && !Journal.ChangeTracker.ChangeTrackingEnabled)
                {
                    Journal.StartTracking();
                }
            }
        }

        #endregion

    }
}
