//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, внесенные в этот файл, могут привести к неверному выполнению кода и будут потеряны
//     в случае его повторного формирования.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Horizont.Claims.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CommonClaim))]
    [KnownType(typeof(Journal))]
    [KnownType(typeof(FailuresGroup))]
    public partial class CommonFailure: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Свойства-примитивы
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("Свойство Id является частью ключа объекта, поэтому его нельзя изменить. Ключевые свойства можно изменять только в тех случаях, когда объект не отслеживается или находится в состоянии добавления.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public Nullable<int> ExecutedPeriod
        {
            get { return _executedPeriod; }
            set
            {
                if (_executedPeriod != value)
                {
                    _executedPeriod = value;
                    OnPropertyChanged("ExecutedPeriod");
                }
            }
        }
        private Nullable<int> _executedPeriod;
    
        [DataMember]
        public Nullable<int> JournalId
        {
            get { return _journalId; }
            set
            {
                if (_journalId != value)
                {
                    ChangeTracker.RecordOriginalValue("JournalId", _journalId);
                    if (!IsDeserializing)
                    {
                        if (Journal != null && Journal.Id != value)
                        {
                            Journal = null;
                        }
                    }
                    _journalId = value;
                    OnPropertyChanged("JournalId");
                }
            }
        }
        private Nullable<int> _journalId;
    
        [DataMember]
        public Nullable<int> Spec
        {
            get { return _spec; }
            set
            {
                if (_spec != value)
                {
                    _spec = value;
                    OnPropertyChanged("Spec");
                }
            }
        }
        private Nullable<int> _spec;

        #endregion

        #region Сложные свойства
    
        [DataMember]
        public RecordInfoType RecordInfo
        {
            get
            {
                if (!_recordInfoInitialized && _recordInfo == null)
                {
                    _recordInfo = new RecordInfoType();
                    ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging += HandleRecordInfoChanging;
                }
                _recordInfoInitialized = true;
                return _recordInfo;
            }
            set
            {
                _recordInfoInitialized = true;
                if (!Equals(_recordInfo, value))
                {
                    if (_recordInfo != null)
                    {
                        ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging -= HandleRecordInfoChanging;
                    }
    
                    HandleRecordInfoChanging(this, null);
                    _recordInfo = value;
                    OnPropertyChanged("RecordInfo");
    
                    if (value != null)
                    {
                        ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging += HandleRecordInfoChanging;
                    }
                }
            }
        }
        private RecordInfoType _recordInfo;
        private bool _recordInfoInitialized;

        #endregion

        #region Свойства навигации
    
        [DataMember]
        public TrackableCollection<CommonClaim> CommonClaims
        {
            get
            {
                if (_commonClaims == null)
                {
                    _commonClaims = new TrackableCollection<CommonClaim>();
                    _commonClaims.CollectionChanged += FixupCommonClaims;
                }
                return _commonClaims;
            }
            set
            {
                if (!ReferenceEquals(_commonClaims, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_commonClaims != null)
                    {
                        _commonClaims.CollectionChanged -= FixupCommonClaims;
                    }
                    _commonClaims = value;
                    if (_commonClaims != null)
                    {
                        _commonClaims.CollectionChanged += FixupCommonClaims;
                    }
                    OnNavigationPropertyChanged("CommonClaims");
                }
            }
        }
        private TrackableCollection<CommonClaim> _commonClaims;
    
        [DataMember]
        public Journal Journal
        {
            get { return _journal; }
            set
            {
                if (!ReferenceEquals(_journal, value))
                {
                    var previousValue = _journal;
                    _journal = value;
                    FixupJournal(previousValue);
                    OnNavigationPropertyChanged("Journal");
                }
            }
        }
        private Journal _journal;
    
        [DataMember]
        public TrackableCollection<FailuresGroup> FailuresGroup
        {
            get
            {
                if (_failuresGroup == null)
                {
                    _failuresGroup = new TrackableCollection<FailuresGroup>();
                    _failuresGroup.CollectionChanged += FixupFailuresGroup;
                }
                return _failuresGroup;
            }
            set
            {
                if (!ReferenceEquals(_failuresGroup, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_failuresGroup != null)
                    {
                        _failuresGroup.CollectionChanged -= FixupFailuresGroup;
                    }
                    _failuresGroup = value;
                    if (_failuresGroup != null)
                    {
                        _failuresGroup.CollectionChanged += FixupFailuresGroup;
                    }
                    OnNavigationPropertyChanged("FailuresGroup");
                }
            }
        }
        private TrackableCollection<FailuresGroup> _failuresGroup;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
        // Записывает исходные значения для сложного свойства RecordInfo
        private void HandleRecordInfoChanging(object sender, EventArgs args)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
        }
    
    
        protected virtual void ClearNavigationProperties()
        {
            CommonClaims.Clear();
            Journal = null;
            FailuresGroup.Clear();
        }

        #endregion

        #region Исправление ассоциаций
    
        private void FixupJournal(Journal previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.CommonFailures.Contains(this))
            {
                previousValue.CommonFailures.Remove(this);
            }
    
            if (Journal != null)
            {
                if (!Journal.CommonFailures.Contains(this))
                {
                    Journal.CommonFailures.Add(this);
                }
    
                JournalId = Journal.Id;
            }
            else if (!skipKeys)
            {
                JournalId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Journal")
                    && (ChangeTracker.OriginalValues["Journal"] == Journal))
                {
                    ChangeTracker.OriginalValues.Remove("Journal");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Journal", previousValue);
                }
                if (Journal != null && !Journal.ChangeTracker.ChangeTrackingEnabled)
                {
                    Journal.StartTracking();
                }
            }
        }
    
        private void FixupCommonClaims(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CommonClaim item in e.NewItems)
                {
                    item.CommonFailure = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CommonClaims", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CommonClaim item in e.OldItems)
                {
                    if (ReferenceEquals(item.CommonFailure, this))
                    {
                        item.CommonFailure = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CommonClaims", item);
                    }
                }
            }
        }
    
        private void FixupFailuresGroup(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FailuresGroup item in e.NewItems)
                {
                    if (!item.CommonFailures.Contains(this))
                    {
                        item.CommonFailures.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FailuresGroup", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FailuresGroup item in e.OldItems)
                {
                    if (item.CommonFailures.Contains(this))
                    {
                        item.CommonFailures.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FailuresGroup", item);
                    }
                }
            }
        }

        #endregion

    }
}
