//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, внесенные в этот файл, могут привести к неверному выполнению кода и будут потеряны
//     в случае его повторного формирования.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Horizont.Claims.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CommonClaim))]
    [KnownType(typeof(CommonClaimHistoryItem))]
    [KnownType(typeof(CommonFailure))]
    [KnownType(typeof(Executor))]
    [KnownType(typeof(FailuresGroup))]
    [KnownType(typeof(Disp))]
    public partial class Journal: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Свойства-примитивы
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("Свойство Id является частью ключа объекта, поэтому его нельзя изменить. Ключевые свойства можно изменять только в тех случаях, когда объект не отслеживается или находится в состоянии добавления.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;

        #endregion

        #region Сложные свойства
    
        [DataMember]
        public RecordInfoType RecordInfo
        {
            get
            {
                if (!_recordInfoInitialized && _recordInfo == null)
                {
                    _recordInfo = new RecordInfoType();
                    ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging += HandleRecordInfoChanging;
                }
                _recordInfoInitialized = true;
                return _recordInfo;
            }
            set
            {
                _recordInfoInitialized = true;
                if (!Equals(_recordInfo, value))
                {
                    if (_recordInfo != null)
                    {
                        ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging -= HandleRecordInfoChanging;
                    }
    
                    HandleRecordInfoChanging(this, null);
                    _recordInfo = value;
                    OnPropertyChanged("RecordInfo");
    
                    if (value != null)
                    {
                        ((INotifyComplexPropertyChanging)_recordInfo).ComplexPropertyChanging += HandleRecordInfoChanging;
                    }
                }
            }
        }
        private RecordInfoType _recordInfo;
        private bool _recordInfoInitialized;

        #endregion

        #region Свойства навигации
    
        [DataMember]
        public TrackableCollection<CommonClaim> CommonClaims
        {
            get
            {
                if (_commonClaims == null)
                {
                    _commonClaims = new TrackableCollection<CommonClaim>();
                    _commonClaims.CollectionChanged += FixupCommonClaims;
                }
                return _commonClaims;
            }
            set
            {
                if (!ReferenceEquals(_commonClaims, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_commonClaims != null)
                    {
                        _commonClaims.CollectionChanged -= FixupCommonClaims;
                    }
                    _commonClaims = value;
                    if (_commonClaims != null)
                    {
                        _commonClaims.CollectionChanged += FixupCommonClaims;
                    }
                    OnNavigationPropertyChanged("CommonClaims");
                }
            }
        }
        private TrackableCollection<CommonClaim> _commonClaims;
    
        [DataMember]
        public TrackableCollection<CommonClaimHistoryItem> CommonClaimsHistories
        {
            get
            {
                if (_commonClaimsHistories == null)
                {
                    _commonClaimsHistories = new TrackableCollection<CommonClaimHistoryItem>();
                    _commonClaimsHistories.CollectionChanged += FixupCommonClaimsHistories;
                }
                return _commonClaimsHistories;
            }
            set
            {
                if (!ReferenceEquals(_commonClaimsHistories, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_commonClaimsHistories != null)
                    {
                        _commonClaimsHistories.CollectionChanged -= FixupCommonClaimsHistories;
                    }
                    _commonClaimsHistories = value;
                    if (_commonClaimsHistories != null)
                    {
                        _commonClaimsHistories.CollectionChanged += FixupCommonClaimsHistories;
                    }
                    OnNavigationPropertyChanged("CommonClaimsHistories");
                }
            }
        }
        private TrackableCollection<CommonClaimHistoryItem> _commonClaimsHistories;
    
        [DataMember]
        public TrackableCollection<CommonFailure> CommonFailures
        {
            get
            {
                if (_commonFailures == null)
                {
                    _commonFailures = new TrackableCollection<CommonFailure>();
                    _commonFailures.CollectionChanged += FixupCommonFailures;
                }
                return _commonFailures;
            }
            set
            {
                if (!ReferenceEquals(_commonFailures, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_commonFailures != null)
                    {
                        _commonFailures.CollectionChanged -= FixupCommonFailures;
                    }
                    _commonFailures = value;
                    if (_commonFailures != null)
                    {
                        _commonFailures.CollectionChanged += FixupCommonFailures;
                    }
                    OnNavigationPropertyChanged("CommonFailures");
                }
            }
        }
        private TrackableCollection<CommonFailure> _commonFailures;
    
        [DataMember]
        public TrackableCollection<Executor> Executors
        {
            get
            {
                if (_executors == null)
                {
                    _executors = new TrackableCollection<Executor>();
                    _executors.CollectionChanged += FixupExecutors;
                }
                return _executors;
            }
            set
            {
                if (!ReferenceEquals(_executors, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_executors != null)
                    {
                        _executors.CollectionChanged -= FixupExecutors;
                    }
                    _executors = value;
                    if (_executors != null)
                    {
                        _executors.CollectionChanged += FixupExecutors;
                    }
                    OnNavigationPropertyChanged("Executors");
                }
            }
        }
        private TrackableCollection<Executor> _executors;
    
        [DataMember]
        public TrackableCollection<FailuresGroup> FailuresGroups
        {
            get
            {
                if (_failuresGroups == null)
                {
                    _failuresGroups = new TrackableCollection<FailuresGroup>();
                    _failuresGroups.CollectionChanged += FixupFailuresGroups;
                }
                return _failuresGroups;
            }
            set
            {
                if (!ReferenceEquals(_failuresGroups, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_failuresGroups != null)
                    {
                        _failuresGroups.CollectionChanged -= FixupFailuresGroups;
                    }
                    _failuresGroups = value;
                    if (_failuresGroups != null)
                    {
                        _failuresGroups.CollectionChanged += FixupFailuresGroups;
                    }
                    OnNavigationPropertyChanged("FailuresGroups");
                }
            }
        }
        private TrackableCollection<FailuresGroup> _failuresGroups;
    
        [DataMember]
        public TrackableCollection<Disp> Disps
        {
            get
            {
                if (_disps == null)
                {
                    _disps = new TrackableCollection<Disp>();
                    _disps.CollectionChanged += FixupDisps;
                }
                return _disps;
            }
            set
            {
                if (!ReferenceEquals(_disps, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Не удается задать FixupChangeTrackingCollection, если включено ChangeTracking");
                    }
                    if (_disps != null)
                    {
                        _disps.CollectionChanged -= FixupDisps;
                    }
                    _disps = value;
                    if (_disps != null)
                    {
                        _disps.CollectionChanged += FixupDisps;
                    }
                    OnNavigationPropertyChanged("Disps");
                }
            }
        }
        private TrackableCollection<Disp> _disps;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
        // Записывает исходные значения для сложного свойства RecordInfo
        private void HandleRecordInfoChanging(object sender, EventArgs args)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
        }
    
    
        protected virtual void ClearNavigationProperties()
        {
            CommonClaims.Clear();
            CommonClaimsHistories.Clear();
            CommonFailures.Clear();
            Executors.Clear();
            FailuresGroups.Clear();
            Disps.Clear();
        }

        #endregion

        #region Исправление ассоциаций
    
        private void FixupCommonClaims(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CommonClaim item in e.NewItems)
                {
                    item.Journal = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CommonClaims", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CommonClaim item in e.OldItems)
                {
                    if (ReferenceEquals(item.Journal, this))
                    {
                        item.Journal = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CommonClaims", item);
                    }
                }
            }
        }
    
        private void FixupCommonClaimsHistories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CommonClaimHistoryItem item in e.NewItems)
                {
                    item.Journal = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CommonClaimsHistories", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CommonClaimHistoryItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.Journal, this))
                    {
                        item.Journal = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CommonClaimsHistories", item);
                    }
                }
            }
        }
    
        private void FixupCommonFailures(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CommonFailure item in e.NewItems)
                {
                    item.Journal = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CommonFailures", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CommonFailure item in e.OldItems)
                {
                    if (ReferenceEquals(item.Journal, this))
                    {
                        item.Journal = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CommonFailures", item);
                    }
                }
            }
        }
    
        private void FixupExecutors(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Executor item in e.NewItems)
                {
                    item.Journal = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Executors", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Executor item in e.OldItems)
                {
                    if (ReferenceEquals(item.Journal, this))
                    {
                        item.Journal = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Executors", item);
                    }
                }
            }
        }
    
        private void FixupFailuresGroups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FailuresGroup item in e.NewItems)
                {
                    item.Journal = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FailuresGroups", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FailuresGroup item in e.OldItems)
                {
                    if (ReferenceEquals(item.Journal, this))
                    {
                        item.Journal = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FailuresGroups", item);
                    }
                }
            }
        }
    
        private void FixupDisps(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Disp item in e.NewItems)
                {
                    if (!item.Journals.Contains(this))
                    {
                        item.Journals.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Disps", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Disp item in e.OldItems)
                {
                    if (item.Journals.Contains(this))
                    {
                        item.Journals.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Disps", item);
                    }
                }
            }
        }

        #endregion

    }
}
