//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, внесенные в этот файл, могут привести к неверному выполнению кода и будут потеряны
//     в случае его повторного формирования.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Horizont.Elv.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Lift))]
    public partial class LiftEvent: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Свойства-примитивы
    
        [DataMember]
        public Nullable<System.DateTime> BreakTime
        {
            get { return _breakTime; }
            set
            {
                if (_breakTime != value)
                {
                    _breakTime = value;
                    OnPropertyChanged("BreakTime");
                }
            }
        }
        private Nullable<System.DateTime> _breakTime;
    
        [DataMember]
        public int LiftId
        {
            get { return _liftId; }
            set
            {
                if (_liftId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("Свойство LiftId является частью ключа объекта, поэтому его нельзя изменить. Ключевые свойства можно изменять только в тех случаях, когда объект не отслеживается или находится в состоянии добавления.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Lift != null && Lift.Id != value)
                        {
                            Lift = null;
                        }
                    }
                    _liftId = value;
                    OnPropertyChanged("LiftId");
                }
            }
        }
        private int _liftId;
    
        [DataMember]
        public bool IsBreak
        {
            get { return _isBreak; }
            set
            {
                if (_isBreak != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("Свойство IsBreak является частью ключа объекта, поэтому его нельзя изменить. Ключевые свойства можно изменять только в тех случаях, когда объект не отслеживается или находится в состоянии добавления.");
                    }
                    _isBreak = value;
                    OnPropertyChanged("IsBreak");
                }
            }
        }
        private bool _isBreak;
    
        [DataMember]
        public string Reason
        {
            get { return _reason; }
            set
            {
                if (_reason != value)
                {
                    _reason = value;
                    OnPropertyChanged("Reason");
                }
            }
        }
        private string _reason;

        #endregion

        #region Свойства навигации
    
        [DataMember]
        public Lift Lift
        {
            get { return _lift; }
            set
            {
                if (!ReferenceEquals(_lift, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Это зависимый конец идентифицирующего отношения, поэтому основной конец изменить нельзя, если он уже задан,
                        // в противном случае для него может быть задана только сущность с первичным ключом, имеющим то же значение, что и у внешнего ключа зависимого элемента.
                        if (LiftId != value.Id)
                        {
                            throw new InvalidOperationException("Основной конец идентифицирующего отношения может быть изменен только тогда, когда зависимый конец находится в состоянии Added.");
                        }
                    }
                    var previousValue = _lift;
                    _lift = value;
                    FixupLift(previousValue);
                    OnNavigationPropertyChanged("Lift");
                }
            }
        }
        private Lift _lift;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // Этот тип сущности является зависимым концом как минимум в одной ассоциации, выполняющей каскадное удаление.
        // Этот обработчик события обрабатывает уведомления, создаваемые при удалении основного конца.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Lift = null;
        }

        #endregion

        #region Исправление ассоциаций
    
        private void FixupLift(Lift previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Events.Contains(this))
            {
                previousValue.Events.Remove(this);
            }
    
            if (Lift != null)
            {
                if (!Lift.Events.Contains(this))
                {
                    Lift.Events.Add(this);
                }
    
                LiftId = Lift.Id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Lift")
                    && (ChangeTracker.OriginalValues["Lift"] == Lift))
                {
                    ChangeTracker.OriginalValues.Remove("Lift");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Lift", previousValue);
                }
                if (Lift != null && !Lift.ChangeTracker.ChangeTrackingEnabled)
                {
                    Lift.StartTracking();
                }
            }
        }

        #endregion

    }
}
